name: media_vault
description: A mobile app that lets you upload your photos and videos to Firebase and group them into albums. Includes fully custom remote and pin-based authentication flow, social sign-in, trash-bin functionality, move/copy assets between albums, asset slider-gallery, export assets to phone gallery and more.

publish_to: "none" 

version: 1.1.7+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  dartz: ^0.10.1
  auto_route: ^7.4.0
  uuid: ^3.0.6
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  flutter_platform_widgets: 4.0.0-beta.1
  google_sign_in: ^6.1.4
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.1
  firebase_storage: ^11.2.3
  video_thumbnail: ^0.5.3
  path_provider: ^2.0.11
  carousel_slider: ^4.1.1
  photo_view: ^0.14.0
  video_player: ^2.6.1
  chewie: ^1.5.0
  cached_network_image: ^3.2.1
  gallery_saver: ^2.3.2
  dio: ^4.0.6
  flutter_cache_manager: ^3.3.0
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.10.0
  flutter_phoenix: ^1.1.0
  firebase_core_platform_interface: ^4.8.0
  wechat_assets_picker: ^8.5.0
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  meta: ^1.8.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.4.5

flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - images/