// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-rZxFT5ktemz9M43EcFFqAWyrCOz2ybc',
    appId: '1:31030779030:web:19a80eb22a6eaf0a5036b7',
    messagingSenderId: '31030779030',
    projectId: 'fe--media-vault',
    authDomain: 'fe--media-vault.firebaseapp.com',
    storageBucket: 'fe--media-vault.appspot.com',
    measurementId: 'G-SJ0S8JSV4L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnkgfKMuGi7613IX3BTvqOni1Q5WDTmAU',
    appId: '1:31030779030:android:ea4fc454e029d2555036b7',
    messagingSenderId: '31030779030',
    projectId: 'fe--media-vault',
    storageBucket: 'fe--media-vault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvqQZJB0EBJT5mq0Y5Z8qTDSb64KaCvqg',
    appId: '1:31030779030:ios:feab506f781a31c85036b7',
    messagingSenderId: '31030779030',
    projectId: 'fe--media-vault',
    storageBucket: 'fe--media-vault.appspot.com',
    iosClientId: '31030779030-ej3jprjqqjb1faaup142lkpm68kfmujn.apps.googleusercontent.com',
    iosBundleId: 'com.finnevermann.mediavault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvqQZJB0EBJT5mq0Y5Z8qTDSb64KaCvqg',
    appId: '1:31030779030:ios:da83bd3b773ce8345036b7',
    messagingSenderId: '31030779030',
    projectId: 'fe--media-vault',
    storageBucket: 'fe--media-vault.appspot.com',
    iosClientId: '31030779030-ftnrborc9j08s9m3sh5pnre753ota36s.apps.googleusercontent.com',
    iosBundleId: 'com.example.mediaVault',
  );
}
