// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTBYXyrXwBjru_ZgNWCXyD1mANug8zTvs',
    appId: '1:216046168879:web:54d2d0b7bb602b4c89cfda',
    messagingSenderId: '216046168879',
    projectId: 'fe-media-vault',
    authDomain: 'fe-media-vault.firebaseapp.com',
    storageBucket: 'fe-media-vault.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn50_V6s8phW_X-Tlf0q4qnw4IMt1OtU8',
    appId: '1:216046168879:android:14508a8b451246dc89cfda',
    messagingSenderId: '216046168879',
    projectId: 'fe-media-vault',
    storageBucket: 'fe-media-vault.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQP7_FbmF6cfI7PjNvn_n7NC9S3qoqn9c',
    appId: '1:216046168879:ios:2f30ddaaaece205389cfda',
    messagingSenderId: '216046168879',
    projectId: 'fe-media-vault',
    storageBucket: 'fe-media-vault.appspot.com',
    iosClientId: '216046168879-aiok1oqpsbqc56jclkv10cncuj19t5rq.apps.googleusercontent.com',
    iosBundleId: 'com.finnevermann.mediavault',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQP7_FbmF6cfI7PjNvn_n7NC9S3qoqn9c',
    appId: '1:216046168879:ios:6a936ac5cd5b4cc889cfda',
    messagingSenderId: '216046168879',
    projectId: 'fe-media-vault',
    storageBucket: 'fe-media-vault.appspot.com',
    iosClientId: '216046168879-tbqh57uohc4j88jha52rsuqtl6neftdj.apps.googleusercontent.com',
    iosBundleId: 'com.finnevermann.mediavault',
  );
}
